In [ ]:
# DATASET FOR PREDICTION

In [6]:
import pandas as pd
import random

In [2]:

locations = ["Delhi", "Mumbai", "Bangalore", "Chennai", "Pune", "Kolkata"]
claim_types = ["Health", "Vehicle", "Property"]

data = []

In [4]:
for i in range(500):
    claim_amount = random.randint(5000, 200000)
    prev_claims = random.randint(0, 5)
    location = random.choice(locations)
    claim_type = random.choice(claim_types)
    
    # Fraud logic (IMPORTANT for ML learning)
    fraud = "Yes" if (claim_amount > 70000 and prev_claims >= 2) else "No"
    
    data.append([
        f"C{i+1:04d}",
        claim_amount,
        claim_type,
        location,
        prev_claims,
        fraud
    ])

df = pd.DataFrame(data, columns=[
    "Customer_ID",
    "Claim_Amount",
    "Claim_Type",
    "Location",
    "Previous_Claims",
    "Fraud"
])

df.to_csv("insurance_claims_large.csv", index=False)

df.head()

  Customer_ID  Claim_Amount Claim_Type   Location  Previous_Claims Fraud
0       C0001         86834    Vehicle      Delhi                4   Yes
1       C0002         17654     Health      Delhi                2    No
2       C0003        102164    Vehicle       Pune                0    No
3       C0004        143454    Vehicle  Bangalore                0    No
4       C0005         10929     Health      Delhi                0    No

In [5]:
df

     Customer_ID  Claim_Amount Claim_Type   Location  Previous_Claims Fraud
0          C0001         86834    Vehicle      Delhi                4   Yes
1          C0002         17654     Health      Delhi                2    No
2          C0003        102164    Vehicle       Pune                0    No
3          C0004        143454    Vehicle  Bangalore                0    No
4          C0005         10929     Health      Delhi                0    No
...          ...           ...        ...        ...              ...   ...
1495       C0496        141597   Property     Mumbai                5   Yes
1496       C0497         46926    Vehicle  Bangalore                1    No
1497       C0498        198278     Health       Pune                1    No
1498       C0499         98194     Health    Kolkata                4   Yes
1499       C0500        195080     Health       Pune                0    No

[1500 rows x 6 columns]

In [7]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df["Claim_Type"] = le.fit_transform(df["Claim_Type"])
df["Location"] = le.fit_transform(df["Location"])
df["Fraud"] = le.fit_transform(df["Fraud"])

In [8]:
df

     Customer_ID  Claim_Amount  Claim_Type  Location  Previous_Claims  Fraud
0          C0001         86834           2         2                4      1
1          C0002         17654           0         2                2      0
2          C0003        102164           2         5                0      0
3          C0004        143454           2         0                0      0
4          C0005         10929           0         2                0      0
...          ...           ...         ...       ...              ...    ...
1495       C0496        141597           1         4                5      1
1496       C0497         46926           2         0                1      0
1497       C0498        198278           0         5                1      0
1498       C0499         98194           0         3                4      1
1499       C0500        195080           0         5                0      0

[1500 rows x 6 columns]